create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  email text,
  avatar_url text,
  interests text[] not null default '{}',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.saved_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id text not null,
  content_type text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique(user_id, content_id)
);

create table if not exists public.recently_viewed (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id text not null,
  viewed_at timestamptz not null default timezone('utc', now()),
  unique(user_id, content_id)
);

create table if not exists public.recently_used_tools (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tool_id text not null,
  used_at timestamptz not null default timezone('utc', now()),
  unique(user_id, tool_id)
);

alter table public.profiles enable row level security;
alter table public.saved_items enable row level security;
alter table public.recently_viewed enable row level security;
alter table public.recently_used_tools enable row level security;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Users can manage their saved items" on public.saved_items;
create policy "Users can manage their saved items" on public.saved_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users can manage recently viewed" on public.recently_viewed;
create policy "Users can manage recently viewed" on public.recently_viewed for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users can manage recently used tools" on public.recently_used_tools;
create policy "Users can manage recently used tools" on public.recently_used_tools for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name, email, avatar_url)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'), new.email, new.raw_user_meta_data->>'avatar_url')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
